### PR TITLE
bugfix: when the --local-addr and --locla-interface being used together, the warning will never be printed.

### PR DESCRIPTION
**Pull request by laixintao**

### CODE REVIEW

**Comment by laixintao** [comment]
@zakird Can you take a look? seems travis disabled for this project

**Comment by spencerdrak** [comment]
Hi @laixintao - only thing is I see there's some conflicts with `master` - if those are resolved then this LGTM.

**Review by dadrian — APPROVED** [review]

**Comment by laixintao** [comment]
resolved.

**Comment by spencerdrak** [comment]
Hi @laixintao - I ran the CI (which now uses github actions to run the integration tests) and they are failing. I believe you should be able to see the output of those tests on this PR, do you mind addressing this and then we'l merge once those are passing? Thanks!

**Comment by laixintao** [comment]
hi @spencerdrak 

the testcase was fixed, passed on my laptop:

```
python -m unittest -v integration_tests.py -k test_local_addr_interface_warning
test_local_addr_interface_warning (integration_tests.Tests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.016s

OK
```

However, github action needs your approval to run.

**Comment by spencerdrak** [comment]
Ran the build with success, everything looks good to me. Merging!

**Pull request merged**
