### PR TITLE
Added --client-subnet for setting EDNS0 option in DNS queries

### PR DESCRIPTION
**Pull request by cj-filip-savin**
You can pass now `--client-subnet` and specify EDNS0 client subnet (RFC 7871)

### CODE REVIEW

**Comment by zakird** [comment]
Thanks for the contribution. I'm excited to see this functionality and overall the code looks good. That said, I'm worried that there's no test coverage — even if whether the code runs. Would you be willing to add a test that calls ZDNS with the new flag and makes sure that the response is sane?

In order to assist with testing, I have created a testing zone that should return different responses. Google Cloud (which hosts zdns-testing.com) only supports Geo-based, so this is the configuration:

Screen Shot 2022-12-17 at 11 19 38 AM

I tested using three subnets belonging to Stanford, TU Munich, and University of Adelaide.

dig ecs-geo.zdns-testing.com +subnet=171.67.68.0/24 @8.8.8.8 => 2.3.4.5
dig ecs-geo.zdns-testing.com +subnet=131.159.92.0/24 @8.8.8.8 => 3.4.5.6
dig ecs-geo.zdns-testing.com +subnet=129.127.149.0/24 @8.8.8.8 => 1.2.3.4

I think that we should be safe to use those subnets in our testing.

Zakir

**Comment by cj-filip-savin** [comment]
Hey, Zakir! I added test for EDNS0 client subnet but spotted that there was bug in `assertEqualAnswers()` and seems I've fixed it in a987a7a47b3cf7f18ba880acae24cb4f57922ca8 , please take a look.

**Review by zakird — APPROVED** [review]

**Comment by cj-filip-savin** [comment]
Thanks for approval. I am not authorized to merge though.

**Comment by zakird** [comment]
Sorry, was waiting for tests to pass after I made that change. Will approve
when I'm back at a computer.

**Comment by cj-filip-savin** [comment]
Thank you, Zakir! I'm switching to use main repo again since this functionality is merged ;)

**Pull request merged**
